const actionTypes = {
  GET_SEARCH_ID: 'GET_SEARCH_ID',
  SUCCESS_FETCHING: 'SUCCESS_FETCHING',
  STOP_FETCHING: 'STOP_FETCHING',
  ERROR_FETCHING: 'ERROR_FETCHING',
  SHOW_MORE_TICKETS: 'SHOW_MORE_TICKETS',
  SORT_BY_PRICE: 'SORT_BY_PRICE',
  SORT_BY_FAST: 'SORT_BY_FAST',
  FILTER_BY_ALL: 'FILTER_BY_ALL',
  FILTER_BY_ZERO: 'FILTER_BY_ZERO',
  FILTER_BY_ONE: 'FILTER_BY_ONE',
  FILTER_BY_TWO: 'FILTER_BY_TWO',
  FILTER_BY_THREE: 'FILTER_BY_THREE',
};

export default actionTypes;
